### ISSUE TITLE
Publish epam/kafka-manager:latest on DockerHub

### ISSUE THREAD

**Issue by eduard93** [epam/eco-kafka-manager#19]
Currently `epam/kafka-manager:latest` is built on a client, but can you please publish it on dockerhub so it can be just pulled?

**Comment by andrei-tytsik** [comment]
@eduard93, good point! We're going to finalize some tasks in current version and then publish the image to Dockerhub. It shouldn't take more than 2 weeks.

**Comment by eduard93** [comment]
Thank you!

**Comment by andrei-tytsik** [comment]
@eduard93, images have been published to Dockerhub.

Please see:
[Dockerhub repo](https://hub.docker.com/r/epam/eco-kafka-manager/tags)
[Running in Docker](https://github.com/epam/eco-kafka-manager/tree/master/ui#running-in-docker)
[Configuration](https://github.com/epam/eco-kafka-manager/tree/master/ui#configuration-properties)

**Comment by andrei-tytsik** [comment]
closing

**Comment by eduard93** [comment]
Thank you!
